name: Update Link Status in README

on:
  push:
    branches:
      - main  # Berjalan otomatis setiap Anda melakukan push ke branch main
  schedule:
    - cron: '0 0 * * *'  # Berjalan otomatis setiap hari jam 12 malam (UTC)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Link Checker Script
        run: |
          chmod +x update_readme.sh
          ./update_readme.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"

          if git diff --quiet README.md; then
            echo "Tidak ada perubahan pada status link."
          else
            git add README.md
            git commit -m "chore: otomatis perbarui status code link di README"
            git push
          fi
